# When we run this system locally in development mode
# what is the patches that you will need?
version: '3'
services:
  web:
    command: npm run dev
    volumes:
      - ./web/:/app/

  mongo-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://username:password@database:27017/