# What all other files will merge with
# Needs to be as simple as possible
version: '3'
services:
  database:
    image: mongo
    env_file: ./.env/database.env
  
  cache:
    image: redis

  web:
    build:
      context: ./web
      dockerfile: Web.Dockerfile
    env_file: ./.env/web.env
    ports:
      - 8080:3000
